In [3]:
import io
import requests
import pandas as pd
import boto3

In [15]:
from tqdm import tqdm

In [4]:
df = pd.read_csv("data/photos.tsv000",sep="\t")
df.head()

,photo_id,photo_url,photo_image_url,photo_submitted_at,photo_featured,photo_width,photo_height,photo_aspect_ratio,photo_description,photographer_username,...,photo_location_longitude,photo_location_country,photo_location_city,stats_views,stats_downloads,ai_description,ai_primary_landmark_name,ai_primary_landmark_latitude,ai_primary_landmark_longitude,ai_primary_landmark_confidence
0,2Q8zDWkj0Yw,https://unsplash.com/photos/2Q8zDWkj0Yw,https://images.unsplash.com/photo-141520117961...,2014-11-05 15:26:26.678711,t,4192,2794,1.50,NaN,lanceanderson,...,NaN,NaN,NaN,15854580,146388,school of jellyfish swimming in body of water,NaN,NaN,NaN,NaN
1,tsBDNuCJiLg,https://unsplash.com/photos/tsBDNuCJiLg,https://images.unsplash.com/photo-141768928330...,2014-12-04 10:31:44.647012,t,4324,2880,1.50,Surfer in the ocean,thehungryjpeg,...,NaN,NaN,NaN,3157825,8247,surfer walking on body of water during daytime,NaN,NaN,NaN,NaN
2,A93gsuMxVcE,https://unsplash.com/photos/A93gsuMxVcE,https://images.unsplash.com/photo-142981401899...,2015-04-23 18:33:44.024841,t,2000,1333,1.50,Barren Countryside,jeremydgreat,...,NaN,NaN,NaN,2159829,7064,landscape photo of road beside field of grass,NaN,NaN,NaN,NaN
3,oYIdH6bFssk,https://unsplash.com/photos/oYIdH6bFssk,https://images.unsplash.com/photo-143275722183...,2015-05-27 20:07:28.35245,t,4288,2848,1.51,Lightbulb reflections,chelaxydp,...,NaN,NaN,NaN,2861489,11778,closed up photo of orange lightened lamp,NaN,NaN,NaN,NaN
4,wgLPy2YBXuc,https://unsplash.com/photos/wgLPy2YBXuc,https://images.unsplash.com/photo-143205996405...,2015-05-19 18:26:15.223161,t,5312,2988,1.78,NaN,csogi,...,NaN,NaN,NaN,6037626,52263,white clouds and blue sky at daytime,NaN,NaN,NaN,NaN

In [8]:
df[["photo_id","photo_image_url"]].head()

array([['2Q8zDWkj0Yw',
        'https://images.unsplash.com/photo-1415201179613-bd037ff5eb29'],
       ['tsBDNuCJiLg',
        'https://images.unsplash.com/photo-1417689283303-02397b2eefe9'],
       ['A93gsuMxVcE',
        'https://images.unsplash.com/photo-1429814018991-71b8981733f4'],
       ['oYIdH6bFssk',
        'https://images.unsplash.com/photo-1432757221830-ad504a69f685'],
       ['wgLPy2YBXuc',
        'https://images.unsplash.com/photo-1432059964050-d4eba2ef368a']],
      dtype=object)

In [9]:
s3 = boto3.client("s3")

In [14]:
for img_id, url in tqdm(df[["photo_id","photo_image_url"]].values,desc="Images Downloaded"):
    resp = requests.get(url)
    b = io.BytesIO(resp.content)
    b.seek(0)
    s3.upload_fileobj(b,"ap-unsplash-images",f"{img_id}.jpg")

array([['2Q8zDWkj0Yw',
        'https://images.unsplash.com/photo-1415201179613-bd037ff5eb29'],
       ['tsBDNuCJiLg',
        'https://images.unsplash.com/photo-1417689283303-02397b2eefe9'],
       ['A93gsuMxVcE',
        'https://images.unsplash.com/photo-1429814018991-71b8981733f4'],
       ...,
       ['GTM-c9mCnCU',
        'https://images.unsplash.com/photo-1591184209368-09d7e848e543'],
       ['6vbYxccNP-o',
        'https://images.unsplash.com/photo-1591509290222-ad64c50fc862'],
       ['TK1z7nRT6aE',
        'https://images.unsplash.com/photo-1591610217257-b3e8b1e99f98']],
      dtype=object)